#! /bin/sh
#

#-- set environment
DSTCDIR=/usr/local/dstc; export DSTCDIR
SYSTYPE=`$DSTCDIR/script/systype`; export SYSTYPE
LD_LIBRARY_PATH=$DSTCDIR/$SYSTYPE/lib; export LD_LIBRARY_PATH
PYTHONPATH=$DSTCDIR/lib/python:$DSTCDIR/$SYSTYPE/lib; export PYTHONPATH

#-- run real script
${DSTCDIR}/${SYSTYPE}/bin/python /home/arnold/work/web-tools/cvs2ticker/cvs2ticker.py ${1+"$@"}
