.\" ***************************************************************
.\" COPYRIGHT_BEGIN
.\"
.\" Copyright (C) 1998-2006 Mantara Software (ABN 17 105 665 594) 
.\" Copyright (C) 2006 David Arnold
.\" All Rights Reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" * Redistributions of source code must retain the above
.\"   copyright notice, this list of conditions and the following
.\"   disclaimer.
.\"
.\" * Redistributions in binary form must reproduce the above
.\"   copyright notice, this list of conditions and the following
.\"   disclaimer in the documentation and/or other materials
.\"   provided with the distribution.
.\"
.\" * Neither the name of Mantara Software nor the names
.\"   of its contributors may be used to endorse or promote
.\"   products derived from this software without specific prior
.\"   written permission. 
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
.\" REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
.\" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\" COPYRIGHT_END
.\" ***************************************************************
.\" 
.\" name      sect foot-centre  foot-left         head-centre
.TH cvs2ticker 1  "28 Sep 2006"  "tickertape.org" "tickertape.org"
.SH NAME
cvs2ticker \- CVS loginfo producer for Tickertape
.SH SYNOPSIS
\fBcvs2ticker\fP \-f config_file | -h | -v
.SH FLAGS
.LP
.TP 4
\-f
Name of configuration file.  Required for normal use.
.TP 4
\-h
Print Usage summary and exit.
.TP 4
\-v
Print version and exit.
.\"
.SH DESCRIPTION
.LP
\fBcvs2ticker\fP generates \fBElvin\fP notifications formatted for
display by \fBTickertape\fP for each commit or import into the
nominated \fBCVS\fP repository.  It parses the stdin passed from CVS
and generates an Elvin notification in Tickertape Chat format.  It
also includes an attachment encapsulating the logged information for
use with the \fBcvs2web\fP.
.\"
.SH EXIT CODES
.lP
.TP 4
0
Completed without error.
.TP 4
1
A problem occurred.  See the debugging output for further information.
.\"
.SH "SEE ALSO"
.LP
.BR cvs (1),
.BR elvin (7),
.BR xtickertape (1)
.LP
http://www.tickertape.org/
.br
http://www.viewvc.org/
.br
http://www.freebsd.org/projects/cvsweb.html
.\"
.SH HISTORY
.LP
Original version by David Leonard.  Further development by the Elvin
Project at DSTC.  Acquired by Mantara Software in 2003, and
subsequently transferred to tickertape.org under a BSD licence.
.\"
.\" ***************************************************************

