#! /bin/sh

echo "cvs2web error:"
echo "This is a dummy file that should be replaced during"
echo "installation.  If you see this when running cvs2web,"
echo "your install broke.  Mail elvin@dstc.com for help."

exit 1
